### ISSUE TITLE
[feature] Add business logic to get machine information by data from a barcode

### ISSUE THREAD

**Issue by Gelassen** [Gelassen/manufactory-knowledge-management-system#6]
### User Story
As a user, I want to scan a barcode and get all information about this machine.

### Tech details
Till this moment network and storage layers should be ready. Ticket scope is to scan and recognize barcode, pull data from the API by barcode and cache it locally. Unit and integration tests are optional. Whole use case integration tests are mandatory, but they would be possible only when UI will be ready. 

Pay special attention to:
- Camera API. My the latest experience shown the right camera API at that moment was [Camera X](https://developer.android.com/media/camera/camerax). However, for passed 15 years of my work with Android, it has been changing 3 times and it is good to keep hand on the pulse.
- ML Kit for barcode scanning.  For more than a decade ZXing library was a de-facto standard for barcode scanners. However android ML kit now offers this feature out of the box. It is interesting to try this library and see if it will be scaled up well among quite old and varied Android devices

#### Security audit

Google products, e.g. Chrome, are known for gathering some user's data and send to Google's servers. Also many corporations are known for abuse of personal data of their customers and/or employees. Therefore using such 3rd party products within our application might be a concern for some corporate customers. Put it on checklist for a security audit to resolve such concerns. 

### Depends on
~~#4 Deliver storage layer~~
~~#5 Deliver network layer~~

**Comment by Gelassen** [comment]
Delegating code scanning to [Google 3rd party app](https://developers.google.com/ml-kit/vision/barcode-scanning/code-scanner) might be a good option, but some Android devices like Xiaomi might not have installed Google Play services which is required by this app. Also political risks might be an issue  -- Google Play Service is not available in Russia via browser without VPN.

**Comment by Gelassen** [comment]
Scanning speed depends on image size. 2mb image is a maximum reasonable size, even smaller images might work out.
Also some important changes in done over migration of Camera API. 

Ref. https://developers.google.com/ml-kit/vision/barcode-scanning/android

```CameraX``` is the newest, but might not be supported by the widest range of devices. However this page claims it is supported by all devices since Android 5

Ref. https://developer.android.com/media/camera/camerax/devices

**Comment by Gelassen** [comment]
"If you use the [CameraX](https://developer.android.com/jetpack/androidx/releases/camera) API, be sure that backpressure strategy is set to its default value[ ImageAnalysis.STRATEGY_KEEP_ONLY_LATEST](https://developer.android.com/reference/androidx/camera/core/ImageAnalysis#STRATEGY_KEEP_ONLY_LATEST). This guarantees only one image will be delivered for analysis at a time. If more images are produced when the analyzer is busy, they will be dropped automatically and not queued for delivery. Once the image being analyzed is closed by calling ImageProxy.close(), the next latest image will be delivered."

Ref. https://developers.google.com/ml-kit/vision/barcode-scanning/android

**Comment by Gelassen** [comment]
Google roadmap is to migrate on ```ksp``` and Compose. While I support ```ksp```, I do not want to migrate on Compose (at least for now). Only 12 from 100 positions  requires it. Their benefits are subtle compare to it fully breaks a dev UX on Android. 

Unfortunately, some libs like ```DataBinding``` depends on ```kapt``` and are not supported with ```ksp``` (and in case ```DataBinding``` never will). It means we have to choose between ```DataBinding``` and ```kapt``` or ```ksp``` but without ```DataBinding```. Dev decision so far drop support of ```DataBinding``` for this project.

**Comment by Gelassen** [comment]
Open question/issue:
https://stackoverflow.com/questions/78120863/dagger-cycle-dependency-issue-for-viewmodelfactory-and-androidinjection

**Comment by Gelassen** [comment]
Opened related issue in dagger repo:
https://github.com/google/dagger/issues/4258

**Comment by Gelassen** [comment]
Clear traffic has been turned on for development purposes:
https://developer.android.com/privacy-and-security/risks/cleartext
https://developer.android.com/privacy-and-security/security-config

It is security hole which should be spot by security analyzers and be in security checklist. Ref #8

**Comment by Gelassen** [comment]
Current WIP version has several Heizenbugs, one of them might be linked to ksp alfa version.

**Comment by Gelassen** [comment]
Known issue on launch:
```
rocess: io.github.gelassen.manufactory_knowledge_management, PID: 19376
                                                                                                    java.lang.IllegalArgumentException: Navigation action/destination io.github.gelassen.manufactory_knowledge_management:id/action_scanner_to_machines cannot be found from the current destination Destination(io.github.gelassen.manufactory_knowledge_management:id/machines_fragment) label=MachinesLabel class=io.github.gelassen.manufactory_knowledge_management.ui.MachineFragment
                                                                                                    	at androidx.navigation.NavController.navigate(NavController.kt:1691)
                                                                                                    	at androidx.navigation.NavController.navigate(NavController.kt:1609)
                                                                                                    	at androidx.navigation.NavController.navigate(NavController.kt:1591)
                                                                                                    	at androidx.navigation.NavController.navigate(NavController.kt:1574)
                                                                                                    	at io.github.gelassen.manufactory_knowledge_management.ui.ScannerFragment.onSuccessfulBarcodeScan(ScannerFragment.kt:132)
```

**Comment by Gelassen** [comment]
Known issue on launch:
```
java.io.IOException: Failed to load asset path /data/app/~~qxDu1OjYthMyY4NDK11FbA==/io.github.gelassen.manufactory_knowledge_management-DDKIHeZyGk_uNa-6LLDVtQ==/base.apk
                                                                                                    	at android.content.res.ApkAssets.nativeLoad(Native Method)
                                                                                                    	at android.content.res.ApkAssets.<init>(ApkAssets.java:296)
                                                                                                    	at android.content.res.ApkAssets.loadFromPath(ApkAssets.java:145)
                                                                                                    	at android.app.ResourcesManager.loadApkAssets(ResourcesManager.java:544)
                                                                                                    	at android.app.ResourcesManager.loadApkAssets(ResourcesManager.java:513)
```

**Comment by Gelassen** [comment]
Crash on the first start is missed in logcat. Sometimes such things happen, extra try-catch blocks might help. 

Also apply strict mode to spot possible violations.

**Comment by Gelassen** [comment]
Open an issue on the key issue right now:
"I have noticed my app crashes on the first install. Further investigation shows this line of code causes it:

```requestPermissionLauncher.launch(Manifest.permission.CAMERA)```
"
https://stackoverflow.com/questions/78160617/silent-crash-on-requestpermissionlauncher-launchmanifest-permission-camera

**Comment by Gelassen** [comment]
Further investigation shown issue appears at least on Samsung A22 (API 33), but on emulator Pixel 3a (API 34) this issue doesn't exist. 

Here is more about caveats with camera app (publication is almost 10 years old, but still valid): 
https://commonsware.com/blog/2015/06/08/action-image-capture-fallacy.html

Next steps are find a way to test app on others physical devices. Firebase test lab might be an option, take a look also on current state of Genymotion and others potential solutions.

**Comment by Gelassen** [comment]
This crash appears so far only on one Samsung A22s with API 33. Emulators and the rest devices including some 5 years old samsung devices work without issues. However A22s is a main device which is used to verify app behavior, the issue must be fixed on it, therefore I can not merge this branch to the master trunk. 

Commonsware shared some things in either some devices or on the recent Android APIs you must use only default app to work with camera, otherwise you will get ```not found``` exception. This is a thing which should be investigated further.

**Comment by Gelassen** [comment]
The feature is done. For MVP web interface has been adopted to mobile and it is enough for this moment. Implementing native client and extending functionality is possible over explicit demand from a customer.
